/*
 * This source file was generated by the Gradle 'init' task
 */
package music.player;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args){
       
        Scanner scanner = new Scanner(System.in);
        
            System.out.println(new App().getGreeting());
            System.out.println("---------------------------");
            System.out.println("Welcome to the Banking App!");

            //After login
            Ui.printChoices();
           
            scanner.close();
       
    }
}
