/*
 * This source file was generated by the Gradle 'init' task
 */
package music.player;
import java.io.Console;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args){
        // loadInformation();
        Account account = new Account(); 
        Methods methods = new Methods(account);
        Ui ui = new Ui(account);
        Console console = System.console();
        try (Scanner scanner = new Scanner(System.in)) {
            boolean login = false;
            int choice;
            do {

                System.out.println("-------------------");
                System.out.println("Select your options");            
                ui.printLandingPage();
                choice = scanner.nextInt();
                scanner.nextLine();
                
                switch (choice) {
                    case 1:
                        System.out.println("Enter a email");
                        String email = scanner.nextLine();
                        System.out.println("Enter a password");
                        String password = scanner.nextLine();
                        login = methods.validateDetails(email, password);   
                        break;
                    case 2:
                    methods.setAccountDetails(scanner);
                        break;
                    case 3:
                        break;
                    default:
                        System.out.println("Select a valid input");
                } 
            } while(login == false || choice == 3);
            System.out.println("---------------------------");
            System.out.println("Welcome to the Banking App!");

            //After login
            do { 
                ui.printMainPage();
                choice = scanner.nextInt();
                scanner.nextLine();
                
                switch (choice) {
                    case 1:
                    System.out.println("Enter the amount you would like to deposit");
                    float deposit = scanner.nextFloat();
                    scanner.nextLine();
                    account.depost(deposit);
                    break;
                case 2:
                System.out.println("Enter the amount you would like to withdraw");
                    break;
                case 3:
                    methods.printAccountDetails();
                    break;
                case 5:
                    break;
                default:
                    System.out.println("Invalid input detected");
                }
            } while (choice != 5);
            
            System.out.println();
        } 
    }
}
